# Generated by Django 4.0.3 on 2022-04-17 19:50

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text 2'),
        ),
    ]
