name: testpypi

on: [ workflow_dispatch ]

jobs:
  TestPyPI:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y gettext
      - uses: actions/setup-python@v4.2.0
      - uses: actions/setup-node@v3.4.1
      - uses: actions/checkout@v3
      - name: Install Javascript dependencies
        working-directory: ./django_ckeditor_5
        run: npm install
      - name: Build ck-editor
        working-directory: ./django_ckeditor_5
        run: npm run prod
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip build wheel twine packaging
      - name: Build dist packages
        run: python -m build --sdist --wheel
      - name: Upload packages
        run: python -m twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}